// import './component-intermediate/state-study-1'
// import './component-intermediate/sol_user-profile'
// import './component-intermediate/state-study-3'
// import './test/test2.js'
// import './component-intermediate/manipulate-list'
// import './component-intermediate/todo-app-demo'
// import './게시물 댓글달기 컴포넌트/index'
// import './use-effect-demo/use-effect-intro'
// import './test/text3'
// import './use-ref-demo/ref-demo'
// import './use-ref-demo/reservation-form'
// import './use-ref-demo/uncontrolled-component'
import './use-ref-demo/use-ref-practice-click-game'